DROP TABLE IF EXISTS "MEvents";
DROP TABLE IF EXISTS "MPlayers";
DROP TABLE IF EXISTS "Cities";
DROP TABLE IF EXISTS "Conferences";
DROP TABLE IF EXISTS "MTeamConferences";
DROP TABLE IF EXISTS "MGameCities";
DROP TABLE IF EXISTS "MMasseyOrdinals";
DROP TABLE IF EXISTS "MNCAATourneyCompactResults";
DROP TABLE IF EXISTS "MNCAATourneyDetailedResults";
DROP TABLE IF EXISTS "MNCAATourneySeeds";
DROP TABLE IF EXISTS "MNCAATourneySlots";
DROP TABLE IF EXISTS "MNCAATourneySeedRoundSlots";
DROP TABLE IF EXISTS "MRegularSeasonCompactResults";
DROP TABLE IF EXISTS "MRegularSeasonDetailedResults";
DROP TABLE IF EXISTS "MSeasons";
DROP TABLE IF EXISTS "MSecondaryTourneyTeams";
DROP TABLE IF EXISTS "MSecondaryTourneyCompactResults";
DROP TABLE IF EXISTS "MTeams";
DROP TABLE IF EXISTS "MTeamConferences";
DROP TABLE IF EXISTS "MTeamCoaches";
DROP TABLE IF EXISTS "WEvents";
DROP TABLE IF EXISTS "WCities";
DROP TABLE IF EXISTS "WConferences";
DROP TABLE IF EXISTS "WGameCities";
DROP TABLE IF EXISTS "WNCAATourneyCompactResults";
DROP TABLE IF EXISTS "WNCAATourneyDetailedResults";
DROP TABLE IF EXISTS "WNCAATourneySeeds";
DROP TABLE IF EXISTS "WNCAATourneySlots";
DROP TABLE IF EXISTS "WPlayers";
DROP TABLE IF EXISTS "WRegularSeasonCompactResults";
DROP TABLE IF EXISTS "WRegularSeasonDetailedResults";
DROP TABLE IF EXISTS "WSeasons";
DROP TABLE IF EXISTS "WTeamConferences";
DROP TABLE IF EXISTS "WTeams";


CREATE TABLE "MEvents" (
	"EventID" DECIMAL NOT NULL, 
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"WFinalScore" DECIMAL NOT NULL, 
	"LFinalScore" DECIMAL NOT NULL, 
	"WCurrentScore" BOOLEAN NOT NULL, 
	"LCurrentScore" BOOLEAN NOT NULL, 
	"ElapsedSeconds" DECIMAL NOT NULL, 
	"EventTeamID" DECIMAL NOT NULL, 
	"EventPlayerID" DECIMAL NOT NULL, 
	"EventType" VARCHAR NOT NULL, 
	"EventSubType" VARCHAR, 
	"X" BOOLEAN NOT NULL, 
	"Y" BOOLEAN NOT NULL, 
	"Area" BOOLEAN NOT NULL
);

CREATE TABLE "MPlayers" (
	"PlayerID" DECIMAL NOT NULL, 
	"LastName" VARCHAR NOT NULL, 
	"FirstName" VARCHAR NOT NULL, 
	"TeamID" DECIMAL NOT NULL
);

CREATE TABLE "Cities" (
	"CityID" DECIMAL NOT NULL, 
	"City" VARCHAR NOT NULL, 
	"State" VARCHAR NOT NULL
);

CREATE TABLE "Conferences" (
	"ConfAbbrev" VARCHAR NOT NULL, 
	"Description" VARCHAR NOT NULL
);
CREATE TABLE "MTeamConferences" (
	"Season" DECIMAL NOT NULL, 
	"TeamID" DECIMAL NOT NULL, 
	"ConfAbbrev" VARCHAR NOT NULL
);
CREATE TABLE "MGameCities" (
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"CRType" VARCHAR NOT NULL, 
	"CityID" DECIMAL NOT NULL
);

CREATE TABLE "MMasseyOrdinals" (
	"Season" DECIMAL NOT NULL, 
	"RankingDayNum" DECIMAL NOT NULL, 
	"SystemName" VARCHAR NOT NULL, 
	"TeamID" DECIMAL NOT NULL, 
	"OrdinalRank" DECIMAL NOT NULL
);


CREATE TABLE "MNCAATourneyCompactResults" (
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"WScore" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"LScore" DECIMAL NOT NULL, 
	"WLoc" BOOLEAN NOT NULL, 
	"NumOT" DECIMAL NOT NULL
);

CREATE TABLE "MNCAATourneyDetailedResults" (
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"WScore" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"LScore" DECIMAL NOT NULL, 
	"WLoc" BOOLEAN NOT NULL, 
	"NumOT" DECIMAL NOT NULL, 
	"WFGM" DECIMAL NOT NULL, 
	"WFGA" DECIMAL NOT NULL, 
	"WFGM3" DECIMAL NOT NULL, 
	"WFGA3" DECIMAL NOT NULL, 
	"WFTM" DECIMAL NOT NULL, 
	"WFTA" DECIMAL NOT NULL, 
	"WOR" DECIMAL NOT NULL, 
	"WDR" DECIMAL NOT NULL, 
	"WAst" DECIMAL NOT NULL, 
	"WTO" DECIMAL NOT NULL, 
	"WStl" DECIMAL NOT NULL, 
	"WBlk" DECIMAL NOT NULL, 
	"WPF" DECIMAL NOT NULL, 
	"LFGM" DECIMAL NOT NULL, 
	"LFGA" DECIMAL NOT NULL, 
	"LFGM3" DECIMAL NOT NULL, 
	"LFGA3" DECIMAL NOT NULL, 
	"LFTM" DECIMAL NOT NULL, 
	"LFTA" DECIMAL NOT NULL, 
	"LOR" DECIMAL NOT NULL, 
	"LDR" DECIMAL NOT NULL, 
	"LAst" DECIMAL NOT NULL, 
	"LTO" DECIMAL NOT NULL, 
	"LStl" DECIMAL NOT NULL, 
	"LBlk" DECIMAL NOT NULL, 
	"LPF" DECIMAL NOT NULL
);
CREATE TABLE "MNCAATourneySeedRoundSlots" (
	"Seed" VARCHAR NOT NULL, 
	"GameRound" DECIMAL NOT NULL, 
	"GameSlot" VARCHAR NOT NULL, 
	"EarlyDayNum" DECIMAL NOT NULL, 
	"LateDayNum" DECIMAL NOT NULL
);
CREATE TABLE "MNCAATourneySeeds" (
	"Season" DECIMAL NOT NULL, 
	"Seed" VARCHAR NOT NULL, 
	"TeamID" DECIMAL NOT NULL
);
CREATE TABLE "MNCAATourneySlots" (
	"Season" DECIMAL NOT NULL, 
	"Slot" VARCHAR NOT NULL, 
	"StrongSeed" VARCHAR NOT NULL, 
	"WeakSeed" VARCHAR NOT NULL
);
CREATE TABLE "MRegularSeasonCompactResults" (
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"WScore" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"LScore" DECIMAL NOT NULL, 
	"WLoc" VARCHAR NOT NULL, 
	"NumOT" DECIMAL NOT NULL
);
CREATE TABLE "MRegularSeasonDetailedResults" (
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"WScore" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"LScore" DECIMAL NOT NULL, 
	"WLoc" VARCHAR NOT NULL, 
	"NumOT" DECIMAL NOT NULL, 
	"WFGM" DECIMAL NOT NULL, 
	"WFGA" DECIMAL NOT NULL, 
	"WFGM3" DECIMAL NOT NULL, 
	"WFGA3" DECIMAL NOT NULL, 
	"WFTM" DECIMAL NOT NULL, 
	"WFTA" DECIMAL NOT NULL, 
	"WOR" DECIMAL NOT NULL, 
	"WDR" DECIMAL NOT NULL, 
	"WAst" DECIMAL NOT NULL, 
	"WTO" DECIMAL NOT NULL, 
	"WStl" DECIMAL NOT NULL, 
	"WBlk" DECIMAL NOT NULL, 
	"WPF" DECIMAL NOT NULL, 
	"LFGM" DECIMAL NOT NULL, 
	"LFGA" DECIMAL NOT NULL, 
	"LFGM3" DECIMAL NOT NULL, 
	"LFGA3" DECIMAL NOT NULL, 
	"LFTM" DECIMAL NOT NULL, 
	"LFTA" DECIMAL NOT NULL, 
	"LOR" DECIMAL NOT NULL, 
	"LDR" DECIMAL NOT NULL, 
	"LAst" DECIMAL NOT NULL, 
	"LTO" DECIMAL NOT NULL, 
	"LStl" DECIMAL NOT NULL, 
	"LBlk" DECIMAL NOT NULL, 
	"LPF" DECIMAL NOT NULL
);
CREATE TABLE "MSeasons" (
	"Season" DECIMAL NOT NULL, 
	"DayZero" DATE NOT NULL, 
	"RegionW" VARCHAR NOT NULL, 
	"RegionX" VARCHAR NOT NULL, 
	"RegionY" VARCHAR NOT NULL, 
	"RegionZ" VARCHAR NOT NULL
);
CREATE TABLE "MSecondaryTourneyCompactResults" (
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"WScore" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"LScore" DECIMAL NOT NULL, 
	"WLoc" VARCHAR NOT NULL, 
	"NumOT" DECIMAL NOT NULL, 
	"SecondaryTourney" VARCHAR NOT NULL
);
CREATE TABLE "MSecondaryTourneyTeams" (
	"Season" DECIMAL NOT NULL, 
	"SecondaryTourney" VARCHAR NOT NULL, 
	"TeamID" DECIMAL NOT NULL
);
CREATE TABLE "MTeamCoaches" (
	"Season" DECIMAL NOT NULL, 
	"TeamID" DECIMAL NOT NULL, 
	"FirstDayNum" DECIMAL NOT NULL, 
	"LastDayNum" DECIMAL NOT NULL, 
	"CoachName" VARCHAR NOT NULL
);
CREATE TABLE "MTeamConferences" (
	"Season" DECIMAL NOT NULL, 
	"TeamID" DECIMAL NOT NULL, 
	"ConfAbbrev" VARCHAR NOT NULL
);
CREATE TABLE "MTeams" (
	"TeamID" DECIMAL NOT NULL, 
	"TeamName" VARCHAR NOT NULL, 
	"FirstD1Season" DECIMAL NOT NULL, 
	"LastD1Season" DECIMAL NOT NULL
);

CREATE TABLE "WEvents" (
	"EventID" DECIMAL NOT NULL, 
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"WFinalScore" DECIMAL NOT NULL, 
	"LFinalScore" DECIMAL NOT NULL, 
	"WCurrentScore" BOOLEAN NOT NULL, 
	"LCurrentScore" BOOLEAN NOT NULL, 
	"ElapsedSeconds" DECIMAL NOT NULL, 
	"EventTeamID" DECIMAL NOT NULL, 
	"EventPlayerID" DECIMAL NOT NULL, 
	"EventType" VARCHAR NOT NULL, 
	"EventSubType" VARCHAR, 
	"X" BOOLEAN NOT NULL, 
	"Y" BOOLEAN NOT NULL, 
	"Area" BOOLEAN NOT NULL
);

CREATE TABLE "WCities" (
	"CityID" DECIMAL NOT NULL, 
	"City" VARCHAR NOT NULL, 
	"State" VARCHAR NOT NULL
);

CREATE TABLE "WConferences" (
	"ConfAbbrev" VARCHAR NOT NULL, 
	"Description" VARCHAR NOT NULL
);

CREATE TABLE "WGameCities" (
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"CRType" VARCHAR NOT NULL, 
	"CityID" DECIMAL NOT NULL
);

CREATE TABLE "WNCAATourneyCompactResults" (
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"WScore" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"LScore" DECIMAL NOT NULL, 
	"WLoc" VARCHAR NOT NULL, 
	"NumOT" DECIMAL NOT NULL
);
CREATE TABLE "WNCAATourneyDetailedResults" (
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"WScore" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"LScore" DECIMAL NOT NULL, 
	"WLoc" VARCHAR NOT NULL, 
	"NumOT" DECIMAL NOT NULL, 
	"WFGM" DECIMAL NOT NULL, 
	"WFGA" DECIMAL NOT NULL, 
	"WFGM3" DECIMAL NOT NULL, 
	"WFGA3" DECIMAL NOT NULL, 
	"WFTM" DECIMAL NOT NULL, 
	"WFTA" DECIMAL NOT NULL, 
	"WOR" DECIMAL NOT NULL, 
	"WDR" DECIMAL NOT NULL, 
	"WAst" DECIMAL NOT NULL, 
	"WTO" DECIMAL NOT NULL, 
	"WStl" DECIMAL NOT NULL, 
	"WBlk" DECIMAL NOT NULL, 
	"WPF" DECIMAL NOT NULL, 
	"LFGM" DECIMAL NOT NULL, 
	"LFGA" DECIMAL NOT NULL, 
	"LFGM3" DECIMAL NOT NULL, 
	"LFGA3" DECIMAL NOT NULL, 
	"LFTM" DECIMAL NOT NULL, 
	"LFTA" DECIMAL NOT NULL, 
	"LOR" DECIMAL NOT NULL, 
	"LDR" DECIMAL NOT NULL, 
	"LAst" DECIMAL NOT NULL, 
	"LTO" DECIMAL NOT NULL, 
	"LStl" DECIMAL NOT NULL, 
	"LBlk" DECIMAL NOT NULL, 
	"LPF" DECIMAL NOT NULL
);
CREATE TABLE "WNCAATourneySeeds" (
	"Season" DECIMAL NOT NULL, 
	"Seed" VARCHAR NOT NULL, 
	"TeamID" DECIMAL NOT NULL
);
CREATE TABLE "WNCAATourneySlots" (
	"Slot" VARCHAR NOT NULL, 
	"StrongSeed" VARCHAR NOT NULL, 
	"WeakSeed" VARCHAR NOT NULL
);
CREATE TABLE "WPlayers" (
	"PlayerID" DECIMAL NOT NULL, 
	"LastName" VARCHAR NOT NULL, 
	"FirstName" VARCHAR NOT NULL, 
	"TeamID" DECIMAL NOT NULL
);
CREATE TABLE "WRegularSeasonCompactResults" (
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"WScore" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"LScore" DECIMAL NOT NULL, 
	"WLoc" VARCHAR NOT NULL, 
	"NumOT" DECIMAL NOT NULL
);
CREATE TABLE "WRegularSeasonDetailedResults" (
	"Season" DECIMAL NOT NULL, 
	"DayNum" DECIMAL NOT NULL, 
	"WTeamID" DECIMAL NOT NULL, 
	"WScore" DECIMAL NOT NULL, 
	"LTeamID" DECIMAL NOT NULL, 
	"LScore" DECIMAL NOT NULL, 
	"WLoc" VARCHAR NOT NULL, 
	"NumOT" DECIMAL NOT NULL, 
	"WFGM" DECIMAL NOT NULL, 
	"WFGA" DECIMAL NOT NULL, 
	"WFGM3" DECIMAL NOT NULL, 
	"WFGA3" DECIMAL NOT NULL, 
	"WFTM" DECIMAL NOT NULL, 
	"WFTA" DECIMAL NOT NULL, 
	"WOR" DECIMAL NOT NULL, 
	"WDR" DECIMAL NOT NULL, 
	"WAst" DECIMAL NOT NULL, 
	"WTO" DECIMAL NOT NULL, 
	"WStl" DECIMAL NOT NULL, 
	"WBlk" DECIMAL NOT NULL, 
	"WPF" DECIMAL NOT NULL, 
	"LFGM" DECIMAL NOT NULL, 
	"LFGA" DECIMAL NOT NULL, 
	"LFGM3" DECIMAL NOT NULL, 
	"LFGA3" DECIMAL NOT NULL, 
	"LFTM" DECIMAL NOT NULL, 
	"LFTA" DECIMAL NOT NULL, 
	"LOR" DECIMAL NOT NULL, 
	"LDR" DECIMAL NOT NULL, 
	"LAst" DECIMAL NOT NULL, 
	"LTO" DECIMAL NOT NULL, 
	"LStl" DECIMAL NOT NULL, 
	"LBlk" DECIMAL NOT NULL, 
	"LPF" DECIMAL NOT NULL
);
CREATE TABLE "WSeasons" (
	"Season" DECIMAL NOT NULL, 
	"DayZero" DATE NOT NULL, 
	"RegionW" VARCHAR NOT NULL, 
	"RegionX" VARCHAR NOT NULL, 
	"RegionY" VARCHAR NOT NULL, 
	"RegionZ" VARCHAR NOT NULL
);
CREATE TABLE "WTeamConferences" (
	"Season" DECIMAL NOT NULL, 
	"TeamID" DECIMAL NOT NULL, 
	"ConfAbbrev" VARCHAR NOT NULL
);
CREATE TABLE "WTeams" (
	"TeamID" DECIMAL NOT NULL, 
	"TeamName" VARCHAR NOT NULL
);





